@"
name: Sync Notion → GitHub Dashboard

on:
  schedule:
    # UTC 00:00 → KST(한국시) 09:00
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Load Notion data
        run: python memory_loader.py

      - name: Generate dashboard
        run: python memory_health_check_all.py

      - name: Commit & push updated dashboard
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto update memory_dashboard.md"
          file_pattern: "memory_dashboard.md"
          branch: "main"

"@ > .github\workflows\sync_notion.yml